apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwave-demo-preppr
  labels:
    app: fwave-demo-preppr
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725896379495
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwave-demo-preppr
  template:
    metadata:
      labels:
        app: fwave-demo-preppr
    spec:
      containers:
        - name: fwave-demo-preppr
          image: acrworkflow1725896379495.azurecr.io/image-workflow-1725896379495:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
