apiVersion: v1
kind: Service
metadata:
  name: fwavedemo
  namespace: namespace-workflow-1725857693654
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: fwavedemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000