apiVersion: v1
kind: Service
metadata:
  name: fwave-demo-preppr
  namespace: namespace-workflow-1725896379495
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: fwave-demo-preppr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000